Fixed an error when Fido returns zero results from the VSO
and some results from at least one other data source. This
(now fixed) error is only present when using numpy version >= 1.23.
